version: "3.6"
services:
    cache:
        image: redis:5-alpine
        networks:
            - cache
        restart: unless-stopped
    db: 
        image: postgres:12-alpine
        environment:
            POSTGRES_DB:
            POSTGRES_DB_FILE:
            POSTGRES_PASSWORD:
            POSTGRES_PASSWORD_FILE:
            POSTGRES_USER:
            POSTGRES_USER_FILE:
        networks:
            - db
        restart: unless-stopped
    uwsgi:
        image: jabberat/hp
        depends_on:
            - cache
            - db
        environment:
            POSTGRES_DB:
            POSTGRES_DB_FILE:
            POSTGRES_PASSWORD:
            POSTGRES_PASSWORD_FILE:
            POSTGRES_USER:
            POSTGRES_USER_FILE:
            DATABASE_HOST:
            DATABASE_PORT:
        networks:
            - cache
            - db
            - external
        ports:
            - 8000:8000
        volumes:
            - ${PWD}/localsettings.yaml:/usr/src/conf/localsettings.yaml

networks:
    external:
    db:
        internal: true
    cache:
        internal: true
