version: "3.6"
services:
    cache:
        image: redis:5-alpine
        networks:
            - cache
        restart: unless-stopped
    db: 
        image: postgres:12-alpine
        environment:
            POSTGRES_DB:
            POSTGRES_DB_FILE:
            POSTGRES_PASSWORD:
            POSTGRES_PASSWORD_FILE:
            POSTGRES_USER:
            POSTGRES_USER_FILE:
        networks:
            - db
        restart: unless-stopped
    celery:
        image: jabberat/hp
        command: /usr/src/hp/celery.sh
        depends_on:
            - cache
            - db
        environment:
            CELERY_LOGLEVEL:
            POSTGRES_DB:
            POSTGRES_DB_FILE:
            POSTGRES_PASSWORD:
            POSTGRES_PASSWORD_FILE:
            POSTGRES_USER:
            POSTGRES_USER_FILE:
        networks:
            - cache
            - db
        volumes:
            - ${PWD}/localsettings.yaml:/usr/src/conf/localsettings.yaml
    uwsgi:
        image: jabberat/hp:${TAG:-latest}
        depends_on:
            - cache
            - db
        environment:
            POSTGRES_DB:
            POSTGRES_DB_FILE:
            POSTGRES_PASSWORD:
            POSTGRES_PASSWORD_FILE:
            POSTGRES_USER:
            POSTGRES_USER_FILE:
            DATABASE_HOST:
            DATABASE_PORT:
        networks:
            - cache
            - db
            - nginx
        volumes:
            - ${PWD}/localsettings.yaml:/usr/src/conf/localsettings.yaml
    nginx:
        image: jabberat/hp-nginx:${TAG:-latest}
        networks:
            - nginx
        ports:
            - 80:80

networks:
    nginx:
    db:
        internal: true
    cache:
        internal: true
