####################################
# jabber.at homepage configuration #
####################################

ALLOWED_HOSTS:
    - localhost
SECRET_KEY: dummy
DEBUG: false

XMPP_HOSTS:
    localhost:
        ALLOWED_HOSTS: localhost
DEFAULT_XMPP_HOST: localhost
