####################################
# jabber.at homepage configuration #
####################################

# List of hostnames where your homepage can be reached
ALLOWED_HOSTS:
    - localhost

# Set this to a unique random value and keep it secret
SECRET_KEY: dummy

#######################
# Email configuration #
#######################
# See also: https://docs.djangoproject.com/en/3.0/topics/email/

# Configure an SMTP server to send emails, see Django documentation for available settings
#EMAIL_HOST: ...
#EMAIL_PORT: ...
#DEFAULT_FROM_EMAIL: user@example.com

# Development: log emails to stdout:
EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
DEFAULT_FROM_EMAIL: hp@localhost

######################
# XMPP configuration #
######################

# Connection to the XMPP server. For more information, see:
#    http://xmpp-backends.readthedocs.io/en/latest/
XMPP_BACKENDS:
    default:
        BACKEND: xmpp_backends.dummy.DummyBackend
        domains: localhost

XMPP_HOSTS:
    localhost:
        ALLOWED_HOSTS: localhost
DEFAULT_XMPP_HOST: localhost
CONTACT_ADDRESS: hp@localhost
